/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cw.train;

import cw.train.storage.DatabaseInitService;

public class App {

    public static void main(String[] args) {
        DatabaseInitService.initDb();
    }
}
